on:
  workflow_call:
    inputs:
      apt-packages:
        required: false
        type: string
      python-version:
        default: "3.12"
        required: false
        type: string

jobs:
  linkcheck:
    env:
      FORCE_COLOR: yes
      UV_CACHE_DIR: ~/.cache/uv
      UV_PYTHON: ${{ inputs.python-version }}
    name: Check external links
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false
      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: uv-doc-${{ runner.os }}-py${{ inputs.python-version }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-doc-${{ runner.os }}-py${{ inputs.python-version }}-${{ hashFiles('uv.lock') }}
            uv-doc-${{ runner.os }}-py${{ inputs.python-version }}
      - if: inputs.apt-packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ${{ inputs.apt-packages }}
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Run Sphinx linkcheck
        run: >-
          uv run \
            --group doc \
            --no-dev \
            --with tox-uv \
            tox -e linkcheck
      - run: uv cache prune --ci
